POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFsYmFuZXoyNiIsImlkIjoiNjdkNTE4OGQ5YTg4M2E5Y2JiOWNkMjk5IiwiaWF0IjoxNzQ5Nzg4ODE2LCJleHAiOjE3NDk3OTYwMTZ9.mw6AKKKdAjD1uuUtVlzuAJKf5Jr4X63M0xmp7VxAsPI

{
  "title": "Some blog with token 5",
  "author": "Miguel Rodriguez",
  "url": "https://someblog.com",
  "likes": 10
}