DELETE http://localhost:3001/api/blogs/67d6648dffb2a4b562f1a9a1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFsYmFuZXoyNiIsImlkIjoiNjdkNTE4OGQ5YTg4M2E5Y2JiOWNkMjk5IiwiaWF0IjoxNzQyMTAyMDAxLCJleHAiOjE3NDIxMDU2MDF9.4bsj666wvfEJREWKnqRMxH35DG7SksSttFqj9b8RQw4